// THIS FILE IS AUTOGENERATED //
#include "../interface/JetGraphTree.h"
// STARTCUSTOM INCLUDE

#include <iostream>

//ENDCUSTOM
JetGraphTree::JetGraphTree() {
// STARTCUSTOM CONSTRUCTOR
// ENDCUSTOM
  Reset();
}
JetGraphTree::~JetGraphTree() {
// STARTCUSTOM DESTRUCTOR
// ENDCUSTOM
}
void JetGraphTree::SetAuxTree(TTree *t) {
// STARTCUSTOM AUX
// ENDCUSTOM
}
void JetGraphTree::Reset() {
// STARTCUSTOM RESET
  for (int iA=0; iA!=NNODE; ++iA) {
    for (int jA=0; jA!=NNODE; ++jA) {
      adj[iA][jA] = false;
    }
  }
// ENDCUSTOM
  runNumber = 0;
  lumiNumber = 0;
  eventNumber = -99;
  jetIdx = 0;
  jetTau32 = -99;
  jetTau21 = -99;
  jetMSD = -99;
  jetPt = -99;
  jetEta = -99;
  jetPhi = -99;
  jetM = -99;
  jetPdgId = 0;
  for (int iA=0; iA!=100; ++iA) {
    nodePt[iA] = -99;
    nodeEta[iA] = -99;
    nodePhi[iA] = -99;
    nodeE[iA] = -99;
    nodeIsFinal[iA] = -99;
    nodeIsRoot[iA] = -99;
  }
}
void JetGraphTree::WriteTree(TTree *t) {
  treePtr = t;
// STARTCUSTOM WRITE
  Book("adj",adj,TString::Format("adj[%i][%i]/O",NNODE,NNODE));
// ENDCUSTOM
  Book("runNumber",&runNumber,"runNumber/I");
  Book("lumiNumber",&lumiNumber,"lumiNumber/I");
  Book("eventNumber",&eventNumber,"eventNumber/l");
  Book("jetIdx",&jetIdx,"jetIdx/I");
  Book("jetTau32",&jetTau32,"jetTau32/F");
  Book("jetTau21",&jetTau21,"jetTau21/F");
  Book("jetMSD",&jetMSD,"jetMSD/F");
  Book("jetPt",&jetPt,"jetPt/F");
  Book("jetEta",&jetEta,"jetEta/F");
  Book("jetPhi",&jetPhi,"jetPhi/F");
  Book("jetM",&jetM,"jetM/F");
  Book("jetPdgId",&jetPdgId,"jetPdgId/I");
  Book("nodePt",nodePt,"nodePt["+TString("100")+"]/F");
  Book("nodeEta",nodeEta,"nodeEta["+TString("100")+"]/F");
  Book("nodePhi",nodePhi,"nodePhi["+TString("100")+"]/F");
  Book("nodeE",nodeE,"nodeE["+TString("100")+"]/F");
  Book("nodeIsFinal",nodeIsFinal,"nodeIsFinal["+TString("100")+"]/F");
  Book("nodeIsRoot",nodeIsRoot,"nodeIsRoot["+TString("100")+"]/F");
}
void JetGraphTree::ReadTree(TTree *t) {
  treePtr = t;
  treePtr->SetBranchStatus("*",0);
// STARTCUSTOM READ
// ENDCUSTOM
  Bind("runNumber",&runNumber);
  Bind("lumiNumber",&lumiNumber);
  Bind("eventNumber",&eventNumber);
  Bind("jetIdx",&jetIdx);
  Bind("jetTau32",&jetTau32);
  Bind("jetTau21",&jetTau21);
  Bind("jetMSD",&jetMSD);
  Bind("jetPt",&jetPt);
  Bind("jetEta",&jetEta);
  Bind("jetPhi",&jetPhi);
  Bind("jetM",&jetM);
  Bind("jetPdgId",&jetPdgId);
  Bind("nodePt",nodePt);
  Bind("nodeEta",nodeEta);
  Bind("nodePhi",nodePhi);
  Bind("nodeE",nodeE);
  Bind("nodeIsFinal",nodeIsFinal);
  Bind("nodeIsRoot",nodeIsRoot);
}