// THIS FILE IS AUTOGENERATED //
#include "../interface/L1Tree.h"
// STARTCUSTOM INCLUDE

#include <iostream>

//ENDCUSTOM
L1Tree::L1Tree() {
// STARTCUSTOM CONSTRUCTOR
// ENDCUSTOM
  Reset();
}
L1Tree::~L1Tree() {
// STARTCUSTOM DESTRUCTOR
// ENDCUSTOM
}
void L1Tree::SetAuxTree(TTree *t) {
// STARTCUSTOM AUX
// ENDCUSTOM
}
void L1Tree::Reset() {
// STARTCUSTOM RESET
// ENDCUSTOM
  runNumber = 0;
  lumiNumber = 0;
  eventNumber = -99;
  met = -99;
  metphi = -99;
  mindphi = 99;
  nJot = 0;
  jot12Mass = -99;
  jot12DEta = -99;
  jot12DPhi = -99;
  for (int iA=0; iA!=3; ++iA) {
    jotPt[iA] = -99;
    jotEta[iA] = -99;
    jotPhi[iA] = -99;
    jotE[iA] = -99;
    jotNEMF[iA] = -99;
    jotNHF[iA] = -99;
    jotL1EGBX[iA] = 99;
    jotL1EGIso[iA] = 0;
    jotL1Pt[iA] = -99;
    jotL1Eta[iA] = -99;
    jotL1Phi[iA] = -99;
    jotL1E[iA] = -99;
  }
}
void L1Tree::WriteTree(TTree *t) {
  treePtr = t;
// STARTCUSTOM WRITE
// ENDCUSTOM
  Book("runNumber",&runNumber,"runNumber/I");
  Book("lumiNumber",&lumiNumber,"lumiNumber/I");
  Book("eventNumber",&eventNumber,"eventNumber/l");
  Book("met",&met,"met/F");
  Book("metphi",&metphi,"metphi/F");
  Book("mindphi",&mindphi,"mindphi/F");
  Book("nJot",&nJot,"nJot/I");
  Book("jotPt",jotPt,"jotPt["+TString("3")+"]/F");
  Book("jotEta",jotEta,"jotEta["+TString("3")+"]/F");
  Book("jotPhi",jotPhi,"jotPhi["+TString("3")+"]/F");
  Book("jotE",jotE,"jotE["+TString("3")+"]/F");
  Book("jotNEMF",jotNEMF,"jotNEMF["+TString("3")+"]/F");
  Book("jotNHF",jotNHF,"jotNHF["+TString("3")+"]/F");
  Book("jotL1EGBX",jotL1EGBX,"jotL1EGBX["+TString("3")+"]/I");
  Book("jotL1EGIso",jotL1EGIso,"jotL1EGIso["+TString("3")+"]/I");
  Book("jotL1Pt",jotL1Pt,"jotL1Pt["+TString("3")+"]/F");
  Book("jotL1Eta",jotL1Eta,"jotL1Eta["+TString("3")+"]/F");
  Book("jotL1Phi",jotL1Phi,"jotL1Phi["+TString("3")+"]/F");
  Book("jotL1E",jotL1E,"jotL1E["+TString("3")+"]/F");
  Book("jot12Mass",&jot12Mass,"jot12Mass/F");
  Book("jot12DEta",&jot12DEta,"jot12DEta/F");
  Book("jot12DPhi",&jot12DPhi,"jot12DPhi/F");
}