// THIS FILE IS AUTOGENERATED //
#include "../interface/L1Tree.h"
// STARTCUSTOM INCLUDE

#include <iostream>

//ENDCUSTOM
L1Tree::L1Tree() {
// STARTCUSTOM CONSTRUCTOR
// ENDCUSTOM
  Reset();
}
L1Tree::~L1Tree() {
// STARTCUSTOM DESTRUCTOR
// ENDCUSTOM
}
void L1Tree::SetAuxTree(TTree *t) {
// STARTCUSTOM AUX
// ENDCUSTOM
}
void L1Tree::Reset() {
// STARTCUSTOM RESET
// ENDCUSTOM
  runNumber = 0;
  lumiNumber = 0;
  eventNumber = -99;
  met = -99;
  metphi = -99;
  mindphi = 99;
  filter = 1;
  nJot = 0;
  nJotEC = 0;
  jot12Mass = -99;
  jot12DEta = -99;
  jot12DPhi = -99;
  for (int iA=0; iA!=4; ++iA) {
    jotPt[iA] = -99;
    jotEta[iA] = -99;
    jotPhi[iA] = -99;
    jotE[iA] = -99;
    jotNEMF[iA] = -99;
    jotNHF[iA] = -99;
    jotL1EGBX[iA] = 99;
    jotL1EGIso[iA] = 0;
    jotL1Pt[iA] = -99;
    jotL1Eta[iA] = -99;
    jotL1Phi[iA] = -99;
  }
  for (int iA=0; iA!=5; ++iA) {
    finor[iA] = -1;
  }
  for (int iA=0; iA!=4; ++iA) {
    l1EGPt[iA] = -99;
    l1EGBX[iA] = 99;
    l1EGEta[iA] = -99;
    l1EGPhi[iA] = -99;
    l1EGIso[iA] = -99;
  }
}
void L1Tree::WriteTree(TTree *t) {
  treePtr = t;
// STARTCUSTOM WRITE
// ENDCUSTOM
  Book("runNumber",&runNumber,"runNumber/I");
  Book("lumiNumber",&lumiNumber,"lumiNumber/I");
  Book("eventNumber",&eventNumber,"eventNumber/l");
  Book("met",&met,"met/F");
  Book("metphi",&metphi,"metphi/F");
  Book("mindphi",&mindphi,"mindphi/F");
  Book("filter",&filter,"filter/I");
  Book("nJot",&nJot,"nJot/I");
  Book("nJotEC",&nJotEC,"nJotEC/I");
  Book("jotPt",jotPt,"jotPt["+TString("4")+"]/F");
  Book("jotEta",jotEta,"jotEta["+TString("4")+"]/F");
  Book("jotPhi",jotPhi,"jotPhi["+TString("4")+"]/F");
  Book("jotE",jotE,"jotE["+TString("4")+"]/F");
  Book("jotNEMF",jotNEMF,"jotNEMF["+TString("4")+"]/F");
  Book("jotNHF",jotNHF,"jotNHF["+TString("4")+"]/F");
  Book("jotL1EGBX",jotL1EGBX,"jotL1EGBX["+TString("4")+"]/I");
  Book("jotL1EGIso",jotL1EGIso,"jotL1EGIso["+TString("4")+"]/I");
  Book("jotL1Pt",jotL1Pt,"jotL1Pt["+TString("4")+"]/F");
  Book("jotL1Eta",jotL1Eta,"jotL1Eta["+TString("4")+"]/F");
  Book("jotL1Phi",jotL1Phi,"jotL1Phi["+TString("4")+"]/F");
  Book("jot12Mass",&jot12Mass,"jot12Mass/F");
  Book("jot12DEta",&jot12DEta,"jot12DEta/F");
  Book("jot12DPhi",&jot12DPhi,"jot12DPhi/F");
  Book("finor",finor,"finor["+TString("5")+"]/I");
  Book("l1EGPt",l1EGPt,"l1EGPt["+TString("4")+"]/F");
  Book("l1EGBX",l1EGBX,"l1EGBX["+TString("4")+"]/I");
  Book("l1EGEta",l1EGEta,"l1EGEta["+TString("4")+"]/F");
  Book("l1EGPhi",l1EGPhi,"l1EGPhi["+TString("4")+"]/F");
  Book("l1EGIso",l1EGIso,"l1EGIso["+TString("4")+"]/F");
}