// THIS FILE IS AUTOGENERATED //
#ifndef EventTree_H
#define EventTree_H
// STARTCUSTOM HEADER

#include "TFile.h"
#include "TTree.h"
#include "TH1D.h"
#include "TLorentzVector.h"
#include "TClonesArray.h"
#include "TString.h"
#include "genericTree.h"
#include <map>

// ENDCUSTOM
class EventTree : public genericTree {
  public:
    EventTree();
    ~EventTree();
    void WriteTree(TTree* t);
    void ReadTree(TTree* t);
    void Fill() { treePtr->Fill(); }
    void Reset();
    void SetAuxTree(TTree*);
// STARTCUSTOM PUBLIC
// ENDCUSTOM
  private:
// STARTCUSTOM PRIVATE
// ENDCUSTOM
  public:
  int runNumber;
  int lumiNumber;
  ULong64_t eventNumber;
  int isData;
  int npv;
  int pu;
  float rho;
  float mcWeight;
};
#endif