// THIS FILE IS AUTOGENERATED //
#ifndef L1Tree_H
#define L1Tree_H
// STARTCUSTOM HEADER

#include "TFile.h"
#include "TTree.h"
#include "TH1D.h"
#include "TLorentzVector.h"
#include "TClonesArray.h"
#include "TString.h"
#include "genericTree.h"
#include <map>

// ENDCUSTOM
#define NL1JET 4
#define NL1EG 4
class L1Tree : public genericTree {
  public:
    L1Tree();
    ~L1Tree();
    void WriteTree(TTree* t);
    void Fill() { treePtr->Fill(); }
    void Reset();    void SetAuxTree(TTree*);
// STARTCUSTOM PUBLIC
// ENDCUSTOM
  private:
// STARTCUSTOM PRIVATE
// ENDCUSTOM
  public:
  int runNumber;
  int lumiNumber;
  ULong64_t eventNumber;
  float met;
  float metphi;
  float mindphi;
  int filter;
  int nJot;
  int nJotEC;
  float jotPt[4];
  float jotEta[4];
  float jotPhi[4];
  float jotE[4];
  float jotNEMF[4];
  float jotNHF[4];
  int jotL1EGBX[4];
  int jotL1EGIso[4];
  float jotL1Pt[4];
  float jotL1Eta[4];
  float jotL1Phi[4];
  float jot12Mass;
  float jot12DEta;
  float jot12DPhi;
  int finor[5];
  float l1EGPt[4];
  int l1EGBX[4];
  float l1EGEta[4];
  float l1EGPhi[4];
  float l1EGIso[4];
};
#endif